/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as FuncionalidadesRouteImport } from './routes/funcionalidades'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSieRouteImport } from './routes/_authenticated/app.sie'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppReturnsRouteImport } from './routes/_authenticated/app.returns'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppRecorrenciaRouteImport } from './routes/_authenticated/app.recorrencia'
import { Route as AuthenticatedAppMensageriaRouteImport } from './routes/_authenticated/app.mensageria'
import { Route as AuthenticatedAppImportRouteImport } from './routes/_authenticated/app.import'
import { Route as AuthenticatedAppFinancialRouteImport } from './routes/_authenticated/app.financial'
import { Route as AuthenticatedAppComunicacaoRouteImport } from './routes/_authenticated/app.comunicacao'
import { Route as AuthenticatedAppClientsRouteImport } from './routes/_authenticated/app.clients'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as ApiPublicHooksJobsTickRouteImport } from './routes/api/public/hooks/jobs-tick'
import { Route as AuthenticatedAppClientsClientIdRouteImport } from './routes/_authenticated/app.clients.$clientId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionalidadesRoute = FuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSieRoute = AuthenticatedAppSieRouteImport.update({
  id: '/sie',
  path: '/sie',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReturnsRoute = AuthenticatedAppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRecorrenciaRoute =
  AuthenticatedAppRecorrenciaRouteImport.update({
    id: '/recorrencia',
    path: '/recorrencia',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMensageriaRoute =
  AuthenticatedAppMensageriaRouteImport.update({
    id: '/mensageria',
    path: '/mensageria',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImportRoute = AuthenticatedAppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFinancialRoute =
  AuthenticatedAppFinancialRouteImport.update({
    id: '/financial',
    path: '/financial',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComunicacaoRoute =
  AuthenticatedAppComunicacaoRouteImport.update({
    id: '/comunicacao',
    path: '/comunicacao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientsRoute = AuthenticatedAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicHooksJobsTickRoute = ApiPublicHooksJobsTickRouteImport.update({
  id: '/api/public/hooks/jobs-tick',
  path: '/api/public/hooks/jobs-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppClientsClientIdRoute =
  AuthenticatedAppClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedAppClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/app/comunicacao': typeof AuthenticatedAppComunicacaoRoute
  '/app/financial': typeof AuthenticatedAppFinancialRoute
  '/app/import': typeof AuthenticatedAppImportRoute
  '/app/mensageria': typeof AuthenticatedAppMensageriaRoute
  '/app/recorrencia': typeof AuthenticatedAppRecorrenciaRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/returns': typeof AuthenticatedAppReturnsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/sie': typeof AuthenticatedAppSieRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/clients/$clientId': typeof AuthenticatedAppClientsClientIdRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/app/comunicacao': typeof AuthenticatedAppComunicacaoRoute
  '/app/financial': typeof AuthenticatedAppFinancialRoute
  '/app/import': typeof AuthenticatedAppImportRoute
  '/app/mensageria': typeof AuthenticatedAppMensageriaRoute
  '/app/recorrencia': typeof AuthenticatedAppRecorrenciaRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/returns': typeof AuthenticatedAppReturnsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/sie': typeof AuthenticatedAppSieRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/clients/$clientId': typeof AuthenticatedAppClientsClientIdRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/_authenticated/app/comunicacao': typeof AuthenticatedAppComunicacaoRoute
  '/_authenticated/app/financial': typeof AuthenticatedAppFinancialRoute
  '/_authenticated/app/import': typeof AuthenticatedAppImportRoute
  '/_authenticated/app/mensageria': typeof AuthenticatedAppMensageriaRoute
  '/_authenticated/app/recorrencia': typeof AuthenticatedAppRecorrenciaRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/returns': typeof AuthenticatedAppReturnsRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/sie': typeof AuthenticatedAppSieRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/clients/$clientId': typeof AuthenticatedAppClientsClientIdRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/funcionalidades'
    | '/planos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/agendar/$slug'
    | '/app/agenda'
    | '/app/clients'
    | '/app/comunicacao'
    | '/app/financial'
    | '/app/import'
    | '/app/mensageria'
    | '/app/recorrencia'
    | '/app/reports'
    | '/app/returns'
    | '/app/services'
    | '/app/settings'
    | '/app/sie'
    | '/app/'
    | '/app/clients/$clientId'
    | '/api/public/hooks/jobs-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/funcionalidades'
    | '/planos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/onboarding'
    | '/agendar/$slug'
    | '/app/agenda'
    | '/app/clients'
    | '/app/comunicacao'
    | '/app/financial'
    | '/app/import'
    | '/app/mensageria'
    | '/app/recorrencia'
    | '/app/reports'
    | '/app/returns'
    | '/app/services'
    | '/app/settings'
    | '/app/sie'
    | '/app'
    | '/app/clients/$clientId'
    | '/api/public/hooks/jobs-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/funcionalidades'
    | '/planos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/agendar/$slug'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/clients'
    | '/_authenticated/app/comunicacao'
    | '/_authenticated/app/financial'
    | '/_authenticated/app/import'
    | '/_authenticated/app/mensageria'
    | '/_authenticated/app/recorrencia'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/returns'
    | '/_authenticated/app/services'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/sie'
    | '/_authenticated/app/'
    | '/_authenticated/app/clients/$clientId'
    | '/api/public/hooks/jobs-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  FuncionalidadesRoute: typeof FuncionalidadesRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiPublicHooksJobsTickRoute: typeof ApiPublicHooksJobsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades': {
      id: '/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof FuncionalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sie': {
      id: '/_authenticated/app/sie'
      path: '/sie'
      fullPath: '/app/sie'
      preLoaderRoute: typeof AuthenticatedAppSieRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/returns': {
      id: '/_authenticated/app/returns'
      path: '/returns'
      fullPath: '/app/returns'
      preLoaderRoute: typeof AuthenticatedAppReturnsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/recorrencia': {
      id: '/_authenticated/app/recorrencia'
      path: '/recorrencia'
      fullPath: '/app/recorrencia'
      preLoaderRoute: typeof AuthenticatedAppRecorrenciaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mensageria': {
      id: '/_authenticated/app/mensageria'
      path: '/mensageria'
      fullPath: '/app/mensageria'
      preLoaderRoute: typeof AuthenticatedAppMensageriaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/import': {
      id: '/_authenticated/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AuthenticatedAppImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financial': {
      id: '/_authenticated/app/financial'
      path: '/financial'
      fullPath: '/app/financial'
      preLoaderRoute: typeof AuthenticatedAppFinancialRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comunicacao': {
      id: '/_authenticated/app/comunicacao'
      path: '/comunicacao'
      fullPath: '/app/comunicacao'
      preLoaderRoute: typeof AuthenticatedAppComunicacaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clients': {
      id: '/_authenticated/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AuthenticatedAppClientsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/jobs-tick': {
      id: '/api/public/hooks/jobs-tick'
      path: '/api/public/hooks/jobs-tick'
      fullPath: '/api/public/hooks/jobs-tick'
      preLoaderRoute: typeof ApiPublicHooksJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/clients/$clientId': {
      id: '/_authenticated/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedAppClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedAppClientsRoute
    }
  }
}

interface AuthenticatedAppClientsRouteChildren {
  AuthenticatedAppClientsClientIdRoute: typeof AuthenticatedAppClientsClientIdRoute
}

const AuthenticatedAppClientsRouteChildren: AuthenticatedAppClientsRouteChildren =
  {
    AuthenticatedAppClientsClientIdRoute: AuthenticatedAppClientsClientIdRoute,
  }

const AuthenticatedAppClientsRouteWithChildren =
  AuthenticatedAppClientsRoute._addFileChildren(
    AuthenticatedAppClientsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppClientsRoute: typeof AuthenticatedAppClientsRouteWithChildren
  AuthenticatedAppComunicacaoRoute: typeof AuthenticatedAppComunicacaoRoute
  AuthenticatedAppFinancialRoute: typeof AuthenticatedAppFinancialRoute
  AuthenticatedAppImportRoute: typeof AuthenticatedAppImportRoute
  AuthenticatedAppMensageriaRoute: typeof AuthenticatedAppMensageriaRoute
  AuthenticatedAppRecorrenciaRoute: typeof AuthenticatedAppRecorrenciaRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppReturnsRoute: typeof AuthenticatedAppReturnsRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSieRoute: typeof AuthenticatedAppSieRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppClientsRoute: AuthenticatedAppClientsRouteWithChildren,
  AuthenticatedAppComunicacaoRoute: AuthenticatedAppComunicacaoRoute,
  AuthenticatedAppFinancialRoute: AuthenticatedAppFinancialRoute,
  AuthenticatedAppImportRoute: AuthenticatedAppImportRoute,
  AuthenticatedAppMensageriaRoute: AuthenticatedAppMensageriaRoute,
  AuthenticatedAppRecorrenciaRoute: AuthenticatedAppRecorrenciaRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppReturnsRoute: AuthenticatedAppReturnsRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSieRoute: AuthenticatedAppSieRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  FuncionalidadesRoute: FuncionalidadesRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiPublicHooksJobsTickRoute: ApiPublicHooksJobsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
